### ISSUE TITLE
connectToStores throws missing static properties error

### ISSUE THREAD

**Issue by peterpme** [altjs/form#1]
I'm trying to copy this example verbatim with no luck.

Are `listenTo` and `getProps` new methods we're supposed to be using in lieu of `getStores`, `getPropsFromStores`?

This is why I was asking about: https://github.com/altjs/connect-to-stores/issues/1

``` js
return {
    listenTo() {
      return [form.store]
    },

    getProps(props) {
      return {
        form: form.getProps({
          name: props.initialName
        })
      }
    },
  }
```

**Comment by goatslacker** [comment]
Both listenTo and getProps are available from this module: https://github.com/altjs/react

npmjs.com/package/alt-react

**Comment by ianks** [comment]
Should this be updated in the README?

**Comment by goatslacker** [comment]
Removed connect example from the README altogether

**Comment by peterpme** [comment]
:)

**Comment by peterpme** [comment]
I'm sorry for not playing a role in this and submitting a PR with updates to that README.

**Comment by goatslacker** [comment]
Oh its ok, thanks for pointing it out that it was confusing.
