### ISSUE TITLE
Getting Started: [bug] save callback not hooking up?

### ISSUE THREAD

**Issue by bryansray** [altjs/form#4]
I'm doing my best to follow the example code from the README, but I'm running in to some issues.

Here is my code:

``` javascript
const form = AltForm('Episode', alt, { fields: ['title', 'description'] });

let Component = React.createClass({
    getInitialState: function() {
        return form.getProps();
    },

    render: function() {
        return <section>
            <h4>New Episode</h4>

            <form>
                <Input type="text" { ...this.state.props.title } />

                <Input type="textarea" { ...this.state.props.description } />

                <Button type="submit" onClick={ this.state.save } className="btn btn-default">Save</Button>
            </form>
        </section>;
    }
});
```

However, when I attempt "Submit" and fire my onClick event. I'm getting to this line of code:

``` javascript
if (callback) callback(null, state);
```

For some reason, alt-form is expecting the callback parameter to be a function. However, in the example code above, it's coming back as a "SyntheticEvent" (click) ...

I feel like I'm missing something? How do I provide that callback parameter?

**Comment by goatslacker** [comment]
``` js
<Button type="submit" onClick={() => this.state.save(aCallbackFunction)} />
```

**Comment by bryansray** [comment]
Am I doing something different from the front page example in the readme? Or is the readme just out dated?

Also, this seems to completely remove the arguments (SynthenticEvent, reactid, etc) from the callback? Is that intended?

**Comment by bryansray** [comment]
ps. Thanks for the response!

**Comment by goatslacker** [comment]
Ooo didn't realize it's on the README. Let me update!
